version: "3.9"

services:
  rabbitmq:
      image: "rabbitmq:3-management"
      ports:
        - "5672:5672"  # RabbitMQ default port
        - "15672:15672"  # RabbitMQ management UI port
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 5s
        timeout: 3s
        retries: 30
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      # Add other configurations for RabbitMQ
      networks:
        - my_network

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    volumes:
      - ./users-service:/var/www/html
    ports:
      - "8000:8000"  # Adjust the port as needed
    environment:
      - APP_ENV=dev
      # Add other environment variables as needed
    depends_on:
      - rabbitmq
    networks:
      - my_network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    volumes:
      - ./notification-service:/var/www/html
    ports:
      - "8081:8081"  # Adjust the port as needed
    environment:
      - APP_ENV=dev
      # Add other environment variables as needed
    depends_on:
       rabbitmq:
        condition: service_healthy
    networks:
      - my_network

  

networks:
  my_network:
